### ISSUE TITLE
Include download.file code in gocomicsrvestr.R to make it reproducible

### ISSUE THREAD

**Issue by bbrewington** [m-a-j/combine#1]
Fellow Calvin & Hobbes fan here, and doing some practice with web scraping with rvest myself.  I'd like to run your code to see what it does, but it looks like you were working with a local copy of the html of the webpages?

Is there a way to code in how you accessed the html?  If you could point me to the source, I'd be glad to help build it in.

**Comment by m-a-j** [comment]
While I am getting a few warning messages that seem unnecessary, the script seems to work fine for me, without having downloaded anything beforehand. Maybe the problem here is `mainDir` - have you tried setting it to another path? It's only there to determine the folder into which the pictures are downloaded.
